
exports.up = function(knex) {
  return knex.schema
    .createTable('cars', async function (table) {
      table.increments('id').primary().notNullable();
      table.string('make', 50);
      table.string('model', 50);
      table.string('year', 50);
    })
    .createTable('countries', async function (table) {
      table.increments('id').primary().notNullable();
      table.string('country_code', 2).notNullable();
      table.string('country_name', 100).notNullable();
    })
    .createTable('images', async function (table) {
      table.increments('id').primary().notNullable();
      table.string('image', 50);
      table.text('description', 65535);
      table.string('category', 12);
      table.string('author', 50);
      table.date('date');
    })
    .createTable('users', async function (table) {
      table.increments('id').primary().notNullable();
      table.string('first_name', 50);
      table.string('last_name', 50);
      table.string('gender', 50);
      table.string('email', 50);
      table.string('company', 50);
      table.string('avatar', 100);
    })


      .then(async function () {
        await knex.transaction(async trx => {
      
          // Process cars
          await trx('cars').del();
          await trx('cars').insert({id:1,make:"Isuzu",model:"Hombre Space",year:"1998"}).onConflict('id').ignore();
          await trx('cars').insert({id:2,make:"Buick",model:"Terraza",year:"2007"}).onConflict('id').ignore();
          await trx('cars').insert({id:3,make:"Mazda",model:"Miata MX-5",year:"1997"}).onConflict('id').ignore();
          await trx('cars').insert({id:4,make:"Ford",model:"Escort",year:"1993"}).onConflict('id').ignore();
          await trx('cars').insert({id:5,make:"Kia",model:"Sedona",year:"2006"}).onConflict('id').ignore();
          await trx('cars').insert({id:6,make:"Acura",model:"TL",year:"2009"}).onConflict('id').ignore();
          await trx('cars').insert({id:7,make:"Dodge",model:"Stealth",year:"1994"}).onConflict('id').ignore();
          await trx('cars').insert({id:8,make:"GMC",model:"Yukon XL",year:"2006"}).onConflict('id').ignore();
          await trx('cars').insert({id:9,make:"Acura",model:"RL",year:"2011"}).onConflict('id').ignore();
          await trx('cars').insert({id:10,make:"Toyota",model:"Prius",year:"2007"}).onConflict('id').ignore();
          await trx('cars').insert({id:11,make:"Mazda",model:"RX-8",year:"2004"}).onConflict('id').ignore();
          await trx('cars').insert({id:12,make:"Dodge",model:"Omni",year:"1978"}).onConflict('id').ignore();
          await trx('cars').insert({id:13,make:"Chevrolet",model:"Malibu",year:"2000"}).onConflict('id').ignore();
          await trx('cars').insert({id:14,make:"Toyota",model:"Tacoma Xtra",year:"1998"}).onConflict('id').ignore();
          await trx('cars').insert({id:15,make:"Mitsubishi",model:"Pajero",year:"1986"}).onConflict('id').ignore();
          await trx('cars').insert({id:16,make:"Oldsmobile",model:"Silhouette",year:"2001"}).onConflict('id').ignore();
          await trx('cars').insert({id:17,make:"Kia",model:"Optima",year:"2012"}).onConflict('id').ignore();
          await trx('cars').insert({id:18,make:"Chevrolet",model:"Lumina",year:"1999"}).onConflict('id').ignore();
          await trx('cars').insert({id:19,make:"Nissan",model:"Versa",year:"2008"}).onConflict('id').ignore();
          await trx('cars').insert({id:20,make:"Lexus",model:"RX",year:"2011"}).onConflict('id').ignore();
      
          // Process countries
          await trx('countries').del();
          await trx('countries').insert({id:1,country_code:"ZW",country_name:"Zimbabwe"}).onConflict('id').ignore();
          await trx('countries').insert({id:2,country_code:"ZM",country_name:"Zambia"}).onConflict('id').ignore();
          await trx('countries').insert({id:3,country_code:"AF",country_name:"Afghanistan"}).onConflict('id').ignore();
          await trx('countries').insert({id:4,country_code:"AL",country_name:"Albania"}).onConflict('id').ignore();
          await trx('countries').insert({id:5,country_code:"DZ",country_name:"Algeria"}).onConflict('id').ignore();
          await trx('countries').insert({id:6,country_code:"DS",country_name:"American Samoa"}).onConflict('id').ignore();
          await trx('countries').insert({id:7,country_code:"AD",country_name:"Andorra"}).onConflict('id').ignore();
          await trx('countries').insert({id:8,country_code:"AO",country_name:"Angola"}).onConflict('id').ignore();
          await trx('countries').insert({id:9,country_code:"AI",country_name:"Anguilla"}).onConflict('id').ignore();
          await trx('countries').insert({id:10,country_code:"AQ",country_name:"Antarctica"}).onConflict('id').ignore();
          await trx('countries').insert({id:11,country_code:"AG",country_name:"Antigua and Barbuda"}).onConflict('id').ignore();
          await trx('countries').insert({id:12,country_code:"AR",country_name:"Argentina"}).onConflict('id').ignore();
          await trx('countries').insert({id:13,country_code:"AM",country_name:"Armenia"}).onConflict('id').ignore();
          await trx('countries').insert({id:14,country_code:"AW",country_name:"Aruba"}).onConflict('id').ignore();
          await trx('countries').insert({id:15,country_code:"AU",country_name:"Australia"}).onConflict('id').ignore();
          await trx('countries').insert({id:16,country_code:"AT",country_name:"Austria"}).onConflict('id').ignore();
          await trx('countries').insert({id:17,country_code:"AZ",country_name:"Azerbaijan"}).onConflict('id').ignore();
          await trx('countries').insert({id:18,country_code:"BS",country_name:"Bahamas"}).onConflict('id').ignore();
          await trx('countries').insert({id:19,country_code:"BH",country_name:"Bahrain"}).onConflict('id').ignore();
          await trx('countries').insert({id:20,country_code:"BD",country_name:"Bangladesh"}).onConflict('id').ignore();
          await trx('countries').insert({id:21,country_code:"BB",country_name:"Barbados"}).onConflict('id').ignore();
          await trx('countries').insert({id:22,country_code:"BY",country_name:"Belarus"}).onConflict('id').ignore();
          await trx('countries').insert({id:23,country_code:"BE",country_name:"Belgium"}).onConflict('id').ignore();
          await trx('countries').insert({id:24,country_code:"BZ",country_name:"Belize"}).onConflict('id').ignore();
          await trx('countries').insert({id:25,country_code:"BJ",country_name:"Benin"}).onConflict('id').ignore();
          await trx('countries').insert({id:26,country_code:"BM",country_name:"Bermuda"}).onConflict('id').ignore();
          await trx('countries').insert({id:27,country_code:"BT",country_name:"Bhutan"}).onConflict('id').ignore();
          await trx('countries').insert({id:28,country_code:"BO",country_name:"Bolivia"}).onConflict('id').ignore();
          await trx('countries').insert({id:29,country_code:"BA",country_name:"Bosnia and Herzegovina"}).onConflict('id').ignore();
          await trx('countries').insert({id:30,country_code:"BW",country_name:"Botswana"}).onConflict('id').ignore();
          await trx('countries').insert({id:31,country_code:"BV",country_name:"Bouvet Island"}).onConflict('id').ignore();
          await trx('countries').insert({id:32,country_code:"BR",country_name:"Brazil"}).onConflict('id').ignore();
          await trx('countries').insert({id:33,country_code:"IO",country_name:"British Indian Ocean Territory"}).onConflict('id').ignore();
          await trx('countries').insert({id:34,country_code:"BN",country_name:"Brunei Darussalam"}).onConflict('id').ignore();
          await trx('countries').insert({id:35,country_code:"BG",country_name:"Bulgaria"}).onConflict('id').ignore();
          await trx('countries').insert({id:36,country_code:"BF",country_name:"Burkina Faso"}).onConflict('id').ignore();
          await trx('countries').insert({id:37,country_code:"BI",country_name:"Burundi"}).onConflict('id').ignore();
          await trx('countries').insert({id:38,country_code:"KH",country_name:"Cambodia"}).onConflict('id').ignore();
          await trx('countries').insert({id:39,country_code:"CM",country_name:"Cameroon"}).onConflict('id').ignore();
          await trx('countries').insert({id:40,country_code:"CA",country_name:"Canada"}).onConflict('id').ignore();
          await trx('countries').insert({id:41,country_code:"CV",country_name:"Cape Verde"}).onConflict('id').ignore();
          await trx('countries').insert({id:42,country_code:"KY",country_name:"Cayman Islands"}).onConflict('id').ignore();
          await trx('countries').insert({id:43,country_code:"CF",country_name:"Central African Republic"}).onConflict('id').ignore();
          await trx('countries').insert({id:44,country_code:"TD",country_name:"Chad"}).onConflict('id').ignore();
          await trx('countries').insert({id:45,country_code:"CL",country_name:"Chile"}).onConflict('id').ignore();
          await trx('countries').insert({id:46,country_code:"CN",country_name:"China"}).onConflict('id').ignore();
          await trx('countries').insert({id:47,country_code:"CX",country_name:"Christmas Island"}).onConflict('id').ignore();
          await trx('countries').insert({id:48,country_code:"CC",country_name:"Cocos (Keeling) Islands"}).onConflict('id').ignore();
          await trx('countries').insert({id:49,country_code:"CO",country_name:"Colombia"}).onConflict('id').ignore();
          await trx('countries').insert({id:50,country_code:"KM",country_name:"Comoros"}).onConflict('id').ignore();
          await trx('countries').insert({id:51,country_code:"CD",country_name:"Democratic Republic of the Congo"}).onConflict('id').ignore();
          await trx('countries').insert({id:52,country_code:"CG",country_name:"Republic of Congo"}).onConflict('id').ignore();
          await trx('countries').insert({id:53,country_code:"CK",country_name:"Cook Islands"}).onConflict('id').ignore();
          await trx('countries').insert({id:54,country_code:"CR",country_name:"Costa Rica"}).onConflict('id').ignore();
          await trx('countries').insert({id:55,country_code:"HR",country_name:"Croatia (Hrvatska)"}).onConflict('id').ignore();
          await trx('countries').insert({id:56,country_code:"CU",country_name:"Cuba"}).onConflict('id').ignore();
          await trx('countries').insert({id:57,country_code:"CY",country_name:"Cyprus"}).onConflict('id').ignore();
          await trx('countries').insert({id:58,country_code:"CZ",country_name:"Czech Republic"}).onConflict('id').ignore();
          await trx('countries').insert({id:59,country_code:"DK",country_name:"Denmark"}).onConflict('id').ignore();
          await trx('countries').insert({id:60,country_code:"DJ",country_name:"Djibouti"}).onConflict('id').ignore();
          await trx('countries').insert({id:61,country_code:"DM",country_name:"Dominica"}).onConflict('id').ignore();
          await trx('countries').insert({id:62,country_code:"DO",country_name:"Dominican Republic"}).onConflict('id').ignore();
          await trx('countries').insert({id:63,country_code:"TP",country_name:"East Timor"}).onConflict('id').ignore();
          await trx('countries').insert({id:64,country_code:"EC",country_name:"Ecuador"}).onConflict('id').ignore();
          await trx('countries').insert({id:65,country_code:"EG",country_name:"Egypt"}).onConflict('id').ignore();
          await trx('countries').insert({id:66,country_code:"SV",country_name:"El Salvador"}).onConflict('id').ignore();
          await trx('countries').insert({id:67,country_code:"GQ",country_name:"Equatorial Guinea"}).onConflict('id').ignore();
          await trx('countries').insert({id:68,country_code:"ER",country_name:"Eritrea"}).onConflict('id').ignore();
          await trx('countries').insert({id:69,country_code:"EE",country_name:"Estonia"}).onConflict('id').ignore();
          await trx('countries').insert({id:70,country_code:"ET",country_name:"Ethiopia"}).onConflict('id').ignore();
          await trx('countries').insert({id:71,country_code:"FK",country_name:"Falkland Islands (Malvinas)"}).onConflict('id').ignore();
          await trx('countries').insert({id:72,country_code:"FO",country_name:"Faroe Islands"}).onConflict('id').ignore();
          await trx('countries').insert({id:73,country_code:"FJ",country_name:"Fiji"}).onConflict('id').ignore();
          await trx('countries').insert({id:74,country_code:"FI",country_name:"Finland"}).onConflict('id').ignore();
          await trx('countries').insert({id:75,country_code:"FR",country_name:"France"}).onConflict('id').ignore();
          await trx('countries').insert({id:76,country_code:"FX",country_name:"France, Metropolitan"}).onConflict('id').ignore();
          await trx('countries').insert({id:77,country_code:"GF",country_name:"French Guiana"}).onConflict('id').ignore();
          await trx('countries').insert({id:78,country_code:"PF",country_name:"French Polynesia"}).onConflict('id').ignore();
          await trx('countries').insert({id:79,country_code:"TF",country_name:"French Southern Territories"}).onConflict('id').ignore();
          await trx('countries').insert({id:80,country_code:"GA",country_name:"Gabon"}).onConflict('id').ignore();
          await trx('countries').insert({id:81,country_code:"GM",country_name:"Gambia"}).onConflict('id').ignore();
          await trx('countries').insert({id:82,country_code:"GE",country_name:"Georgia"}).onConflict('id').ignore();
          await trx('countries').insert({id:83,country_code:"DE",country_name:"Germany"}).onConflict('id').ignore();
          await trx('countries').insert({id:84,country_code:"GH",country_name:"Ghana"}).onConflict('id').ignore();
          await trx('countries').insert({id:85,country_code:"GI",country_name:"Gibraltar"}).onConflict('id').ignore();
          await trx('countries').insert({id:86,country_code:"GK",country_name:"Guernsey"}).onConflict('id').ignore();
          await trx('countries').insert({id:87,country_code:"GR",country_name:"Greece"}).onConflict('id').ignore();
          await trx('countries').insert({id:88,country_code:"GL",country_name:"Greenland"}).onConflict('id').ignore();
          await trx('countries').insert({id:89,country_code:"GD",country_name:"Grenada"}).onConflict('id').ignore();
          await trx('countries').insert({id:90,country_code:"GP",country_name:"Guadeloupe"}).onConflict('id').ignore();
          await trx('countries').insert({id:91,country_code:"GU",country_name:"Guam"}).onConflict('id').ignore();
          await trx('countries').insert({id:92,country_code:"GT",country_name:"Guatemala"}).onConflict('id').ignore();
          await trx('countries').insert({id:93,country_code:"GN",country_name:"Guinea"}).onConflict('id').ignore();
          await trx('countries').insert({id:94,country_code:"GW",country_name:"Guinea-Bissau"}).onConflict('id').ignore();
          await trx('countries').insert({id:95,country_code:"GY",country_name:"Guyana"}).onConflict('id').ignore();
          await trx('countries').insert({id:96,country_code:"HT",country_name:"Haiti"}).onConflict('id').ignore();
          await trx('countries').insert({id:97,country_code:"HM",country_name:"Heard and Mc Donald Islands"}).onConflict('id').ignore();
          await trx('countries').insert({id:98,country_code:"HN",country_name:"Honduras"}).onConflict('id').ignore();
          await trx('countries').insert({id:99,country_code:"HK",country_name:"Hong Kong"}).onConflict('id').ignore();
          await trx('countries').insert({id:100,country_code:"HU",country_name:"Hungary"}).onConflict('id').ignore();
          await trx('countries').insert({id:101,country_code:"IS",country_name:"Iceland"}).onConflict('id').ignore();
          await trx('countries').insert({id:102,country_code:"IN",country_name:"India"}).onConflict('id').ignore();
          await trx('countries').insert({id:103,country_code:"IM",country_name:"Isle of Man"}).onConflict('id').ignore();
          await trx('countries').insert({id:104,country_code:"ID",country_name:"Indonesia"}).onConflict('id').ignore();
          await trx('countries').insert({id:105,country_code:"IR",country_name:"Iran (Islamic Republic of)"}).onConflict('id').ignore();
          await trx('countries').insert({id:106,country_code:"IQ",country_name:"Iraq"}).onConflict('id').ignore();
          await trx('countries').insert({id:107,country_code:"IE",country_name:"Ireland"}).onConflict('id').ignore();
          await trx('countries').insert({id:108,country_code:"IL",country_name:"Israel"}).onConflict('id').ignore();
          await trx('countries').insert({id:109,country_code:"IT",country_name:"Italy"}).onConflict('id').ignore();
          await trx('countries').insert({id:110,country_code:"CI",country_name:"Ivory Coast"}).onConflict('id').ignore();
          await trx('countries').insert({id:111,country_code:"JE",country_name:"Jersey"}).onConflict('id').ignore();
          await trx('countries').insert({id:112,country_code:"JM",country_name:"Jamaica"}).onConflict('id').ignore();
          await trx('countries').insert({id:113,country_code:"JP",country_name:"Japan"}).onConflict('id').ignore();
          await trx('countries').insert({id:114,country_code:"JO",country_name:"Jordan"}).onConflict('id').ignore();
          await trx('countries').insert({id:115,country_code:"KZ",country_name:"Kazakhstan"}).onConflict('id').ignore();
          await trx('countries').insert({id:116,country_code:"KE",country_name:"Kenya"}).onConflict('id').ignore();
          await trx('countries').insert({id:117,country_code:"KI",country_name:"Kiribati"}).onConflict('id').ignore();
          await trx('countries').insert({id:118,country_code:"KP",country_name:"Korea, Democratic People's Republic of"}).onConflict('id').ignore();
          await trx('countries').insert({id:119,country_code:"KR",country_name:"Korea, Republic of"}).onConflict('id').ignore();
          await trx('countries').insert({id:120,country_code:"XK",country_name:"Kosovo"}).onConflict('id').ignore();
          await trx('countries').insert({id:121,country_code:"KW",country_name:"Kuwait"}).onConflict('id').ignore();
          await trx('countries').insert({id:122,country_code:"KG",country_name:"Kyrgyzstan"}).onConflict('id').ignore();
          await trx('countries').insert({id:123,country_code:"LA",country_name:"Lao People's Democratic Republic"}).onConflict('id').ignore();
          await trx('countries').insert({id:124,country_code:"LV",country_name:"Latvia"}).onConflict('id').ignore();
          await trx('countries').insert({id:125,country_code:"LB",country_name:"Lebanon"}).onConflict('id').ignore();
          await trx('countries').insert({id:126,country_code:"LS",country_name:"Lesotho"}).onConflict('id').ignore();
          await trx('countries').insert({id:127,country_code:"LR",country_name:"Liberia"}).onConflict('id').ignore();
          await trx('countries').insert({id:128,country_code:"LY",country_name:"Libyan Arab Jamahiriya"}).onConflict('id').ignore();
          await trx('countries').insert({id:129,country_code:"LI",country_name:"Liechtenstein"}).onConflict('id').ignore();
          await trx('countries').insert({id:130,country_code:"LT",country_name:"Lithuania"}).onConflict('id').ignore();
          await trx('countries').insert({id:131,country_code:"LU",country_name:"Luxembourg"}).onConflict('id').ignore();
          await trx('countries').insert({id:132,country_code:"MO",country_name:"Macau"}).onConflict('id').ignore();
          await trx('countries').insert({id:133,country_code:"MK",country_name:"North Macedonia"}).onConflict('id').ignore();
          await trx('countries').insert({id:134,country_code:"MG",country_name:"Madagascar"}).onConflict('id').ignore();
          await trx('countries').insert({id:135,country_code:"MW",country_name:"Malawi"}).onConflict('id').ignore();
          await trx('countries').insert({id:136,country_code:"MY",country_name:"Malaysia"}).onConflict('id').ignore();
          await trx('countries').insert({id:137,country_code:"MV",country_name:"Maldives"}).onConflict('id').ignore();
          await trx('countries').insert({id:138,country_code:"ML",country_name:"Mali"}).onConflict('id').ignore();
          await trx('countries').insert({id:139,country_code:"MT",country_name:"Malta"}).onConflict('id').ignore();
          await trx('countries').insert({id:140,country_code:"MH",country_name:"Marshall Islands"}).onConflict('id').ignore();
          await trx('countries').insert({id:141,country_code:"MQ",country_name:"Martinique"}).onConflict('id').ignore();
          await trx('countries').insert({id:142,country_code:"MR",country_name:"Mauritania"}).onConflict('id').ignore();
          await trx('countries').insert({id:143,country_code:"MU",country_name:"Mauritius"}).onConflict('id').ignore();
          await trx('countries').insert({id:144,country_code:"TY",country_name:"Mayotte"}).onConflict('id').ignore();
          await trx('countries').insert({id:145,country_code:"MX",country_name:"Mexico"}).onConflict('id').ignore();
          await trx('countries').insert({id:146,country_code:"FM",country_name:"Micronesia, Federated States of"}).onConflict('id').ignore();
          await trx('countries').insert({id:147,country_code:"MD",country_name:"Moldova, Republic of"}).onConflict('id').ignore();
          await trx('countries').insert({id:148,country_code:"MC",country_name:"Monaco"}).onConflict('id').ignore();
          await trx('countries').insert({id:149,country_code:"MN",country_name:"Mongolia"}).onConflict('id').ignore();
          await trx('countries').insert({id:150,country_code:"ME",country_name:"Montenegro"}).onConflict('id').ignore();
          await trx('countries').insert({id:151,country_code:"MS",country_name:"Montserrat"}).onConflict('id').ignore();
          await trx('countries').insert({id:152,country_code:"MA",country_name:"Morocco"}).onConflict('id').ignore();
          await trx('countries').insert({id:153,country_code:"MZ",country_name:"Mozambique"}).onConflict('id').ignore();
          await trx('countries').insert({id:154,country_code:"MM",country_name:"Myanmar"}).onConflict('id').ignore();
          await trx('countries').insert({id:155,country_code:"NA",country_name:"Namibia"}).onConflict('id').ignore();
          await trx('countries').insert({id:156,country_code:"NR",country_name:"Nauru"}).onConflict('id').ignore();
          await trx('countries').insert({id:157,country_code:"NP",country_name:"Nepal"}).onConflict('id').ignore();
          await trx('countries').insert({id:158,country_code:"NL",country_name:"Netherlands"}).onConflict('id').ignore();
          await trx('countries').insert({id:159,country_code:"AN",country_name:"Netherlands Antilles"}).onConflict('id').ignore();
          await trx('countries').insert({id:160,country_code:"NC",country_name:"New Caledonia"}).onConflict('id').ignore();
          await trx('countries').insert({id:161,country_code:"NZ",country_name:"New Zealand"}).onConflict('id').ignore();
          await trx('countries').insert({id:162,country_code:"NI",country_name:"Nicaragua"}).onConflict('id').ignore();
          await trx('countries').insert({id:163,country_code:"NE",country_name:"Niger"}).onConflict('id').ignore();
          await trx('countries').insert({id:164,country_code:"NG",country_name:"Nigeria"}).onConflict('id').ignore();
          await trx('countries').insert({id:165,country_code:"NU",country_name:"Niue"}).onConflict('id').ignore();
          await trx('countries').insert({id:166,country_code:"NF",country_name:"Norfolk Island"}).onConflict('id').ignore();
          await trx('countries').insert({id:167,country_code:"MP",country_name:"Northern Mariana Islands"}).onConflict('id').ignore();
          await trx('countries').insert({id:168,country_code:"NO",country_name:"Norway"}).onConflict('id').ignore();
          await trx('countries').insert({id:169,country_code:"OM",country_name:"Oman"}).onConflict('id').ignore();
          await trx('countries').insert({id:170,country_code:"PK",country_name:"Pakistan"}).onConflict('id').ignore();
          await trx('countries').insert({id:171,country_code:"PW",country_name:"Palau"}).onConflict('id').ignore();
          await trx('countries').insert({id:172,country_code:"PS",country_name:"Palestine"}).onConflict('id').ignore();
          await trx('countries').insert({id:173,country_code:"PA",country_name:"Panama"}).onConflict('id').ignore();
          await trx('countries').insert({id:174,country_code:"PG",country_name:"Papua New Guinea"}).onConflict('id').ignore();
          await trx('countries').insert({id:175,country_code:"PY",country_name:"Paraguay"}).onConflict('id').ignore();
          await trx('countries').insert({id:176,country_code:"PE",country_name:"Peru"}).onConflict('id').ignore();
          await trx('countries').insert({id:177,country_code:"PH",country_name:"Philippines"}).onConflict('id').ignore();
          await trx('countries').insert({id:178,country_code:"PN",country_name:"Pitcairn"}).onConflict('id').ignore();
          await trx('countries').insert({id:179,country_code:"PL",country_name:"Poland"}).onConflict('id').ignore();
          await trx('countries').insert({id:180,country_code:"PT",country_name:"Portugal"}).onConflict('id').ignore();
          await trx('countries').insert({id:181,country_code:"PR",country_name:"Puerto Rico"}).onConflict('id').ignore();
          await trx('countries').insert({id:182,country_code:"QA",country_name:"Qatar"}).onConflict('id').ignore();
          await trx('countries').insert({id:183,country_code:"RE",country_name:"Reunion"}).onConflict('id').ignore();
          await trx('countries').insert({id:184,country_code:"RO",country_name:"Romania"}).onConflict('id').ignore();
          await trx('countries').insert({id:185,country_code:"RU",country_name:"Russian Federation"}).onConflict('id').ignore();
          await trx('countries').insert({id:186,country_code:"RW",country_name:"Rwanda"}).onConflict('id').ignore();
          await trx('countries').insert({id:187,country_code:"KN",country_name:"Saint Kitts and Nevis"}).onConflict('id').ignore();
          await trx('countries').insert({id:188,country_code:"LC",country_name:"Saint Lucia"}).onConflict('id').ignore();
          await trx('countries').insert({id:189,country_code:"VC",country_name:"Saint Vincent and the Grenadines"}).onConflict('id').ignore();
          await trx('countries').insert({id:190,country_code:"WS",country_name:"Samoa"}).onConflict('id').ignore();
          await trx('countries').insert({id:191,country_code:"SM",country_name:"San Marino"}).onConflict('id').ignore();
          await trx('countries').insert({id:192,country_code:"ST",country_name:"Sao Tome and Principe"}).onConflict('id').ignore();
          await trx('countries').insert({id:193,country_code:"SA",country_name:"Saudi Arabia"}).onConflict('id').ignore();
          await trx('countries').insert({id:194,country_code:"SN",country_name:"Senegal"}).onConflict('id').ignore();
          await trx('countries').insert({id:195,country_code:"RS",country_name:"Serbia"}).onConflict('id').ignore();
          await trx('countries').insert({id:196,country_code:"SC",country_name:"Seychelles"}).onConflict('id').ignore();
          await trx('countries').insert({id:197,country_code:"SL",country_name:"Sierra Leone"}).onConflict('id').ignore();
          await trx('countries').insert({id:198,country_code:"SG",country_name:"Singapore"}).onConflict('id').ignore();
          await trx('countries').insert({id:199,country_code:"SK",country_name:"Slovakia"}).onConflict('id').ignore();
          await trx('countries').insert({id:200,country_code:"SI",country_name:"Slovenia"}).onConflict('id').ignore();
          await trx('countries').insert({id:201,country_code:"SB",country_name:"Solomon Islands"}).onConflict('id').ignore();
          await trx('countries').insert({id:202,country_code:"SO",country_name:"Somalia"}).onConflict('id').ignore();
          await trx('countries').insert({id:203,country_code:"ZA",country_name:"South Africa"}).onConflict('id').ignore();
          await trx('countries').insert({id:204,country_code:"GS",country_name:"South Georgia South Sandwich Islands"}).onConflict('id').ignore();
          await trx('countries').insert({id:205,country_code:"SS",country_name:"South Sudan"}).onConflict('id').ignore();
          await trx('countries').insert({id:206,country_code:"ES",country_name:"Spain"}).onConflict('id').ignore();
          await trx('countries').insert({id:207,country_code:"LK",country_name:"Sri Lanka"}).onConflict('id').ignore();
          await trx('countries').insert({id:208,country_code:"SH",country_name:"St. Helena"}).onConflict('id').ignore();
          await trx('countries').insert({id:209,country_code:"PM",country_name:"St. Pierre and Miquelon"}).onConflict('id').ignore();
          await trx('countries').insert({id:210,country_code:"SD",country_name:"Sudan"}).onConflict('id').ignore();
          await trx('countries').insert({id:211,country_code:"SR",country_name:"Suriname"}).onConflict('id').ignore();
          await trx('countries').insert({id:212,country_code:"SJ",country_name:"Svalbard and Jan Mayen Islands"}).onConflict('id').ignore();
          await trx('countries').insert({id:213,country_code:"SZ",country_name:"Swaziland"}).onConflict('id').ignore();
          await trx('countries').insert({id:214,country_code:"SE",country_name:"Sweden"}).onConflict('id').ignore();
          await trx('countries').insert({id:215,country_code:"CH",country_name:"Switzerland"}).onConflict('id').ignore();
          await trx('countries').insert({id:216,country_code:"SY",country_name:"Syrian Arab Republic"}).onConflict('id').ignore();
          await trx('countries').insert({id:217,country_code:"TW",country_name:"Taiwan"}).onConflict('id').ignore();
          await trx('countries').insert({id:218,country_code:"TJ",country_name:"Tajikistan"}).onConflict('id').ignore();
          await trx('countries').insert({id:219,country_code:"TZ",country_name:"Tanzania, United Republic of"}).onConflict('id').ignore();
          await trx('countries').insert({id:220,country_code:"TH",country_name:"Thailand"}).onConflict('id').ignore();
          await trx('countries').insert({id:221,country_code:"TG",country_name:"Togo"}).onConflict('id').ignore();
          await trx('countries').insert({id:222,country_code:"TK",country_name:"Tokelau"}).onConflict('id').ignore();
          await trx('countries').insert({id:223,country_code:"TO",country_name:"Tonga"}).onConflict('id').ignore();
          await trx('countries').insert({id:224,country_code:"TT",country_name:"Trinidad and Tobago"}).onConflict('id').ignore();
          await trx('countries').insert({id:225,country_code:"TN",country_name:"Tunisia"}).onConflict('id').ignore();
          await trx('countries').insert({id:226,country_code:"TR",country_name:"Turkey"}).onConflict('id').ignore();
          await trx('countries').insert({id:227,country_code:"TM",country_name:"Turkmenistan"}).onConflict('id').ignore();
          await trx('countries').insert({id:228,country_code:"TC",country_name:"Turks and Caicos Islands"}).onConflict('id').ignore();
          await trx('countries').insert({id:229,country_code:"TV",country_name:"Tuvalu"}).onConflict('id').ignore();
          await trx('countries').insert({id:230,country_code:"UG",country_name:"Uganda"}).onConflict('id').ignore();
          await trx('countries').insert({id:231,country_code:"UA",country_name:"Ukraine"}).onConflict('id').ignore();
          await trx('countries').insert({id:232,country_code:"AE",country_name:"United Arab Emirates"}).onConflict('id').ignore();
          await trx('countries').insert({id:233,country_code:"GB",country_name:"United Kingdom"}).onConflict('id').ignore();
          await trx('countries').insert({id:234,country_code:"US",country_name:"United States"}).onConflict('id').ignore();
          await trx('countries').insert({id:235,country_code:"UM",country_name:"United States minor outlying islands"}).onConflict('id').ignore();
          await trx('countries').insert({id:236,country_code:"UY",country_name:"Uruguay"}).onConflict('id').ignore();
          await trx('countries').insert({id:237,country_code:"UZ",country_name:"Uzbekistan"}).onConflict('id').ignore();
          await trx('countries').insert({id:238,country_code:"VU",country_name:"Vanuatu"}).onConflict('id').ignore();
          await trx('countries').insert({id:239,country_code:"VA",country_name:"Vatican City State"}).onConflict('id').ignore();
          await trx('countries').insert({id:240,country_code:"VE",country_name:"Venezuela"}).onConflict('id').ignore();
          await trx('countries').insert({id:241,country_code:"VN",country_name:"Vietnam"}).onConflict('id').ignore();
          await trx('countries').insert({id:242,country_code:"VG",country_name:"Virgin Islands (British)"}).onConflict('id').ignore();
          await trx('countries').insert({id:243,country_code:"VI",country_name:"Virgin Islands (U.S.)"}).onConflict('id').ignore();
          await trx('countries').insert({id:244,country_code:"WF",country_name:"Wallis and Futuna Islands"}).onConflict('id').ignore();
          await trx('countries').insert({id:245,country_code:"EH",country_name:"Western Sahara"}).onConflict('id').ignore();
          await trx('countries').insert({id:246,country_code:"YE",country_name:"Yemen"}).onConflict('id').ignore();
      
          // Process images
          await trx('images').del();
          await trx('images').insert({id:1,image:"/assets/img/food-1.jpg",description:"Food photo 1",category:"food",author:"Lily Banse",date:"2018-03-31T22:00:00.000Z"}).onConflict('id').ignore();
          await trx('images').insert({id:2,image:"/assets/img/nature-2.jpg",description:"Nature photo 2",category:"nature",author:"Winn Pellew",date:"2018-07-19T22:00:00.000Z"}).onConflict('id').ignore();
          await trx('images').insert({id:3,image:"/assets/img/wildlife-3.jpg",description:"Wildlife photo 3",category:"wildlife",author:"Kalila Moffat",date:"2019-07-20T22:00:00.000Z"}).onConflict('id').ignore();
          await trx('images').insert({id:4,image:"/assets/img/architecture-1.jpg",description:"Architecture photo 1",category:"architecture",author:"Patrick Tomasso",date:"2016-06-29T22:00:00.000Z"}).onConflict('id').ignore();
          await trx('images').insert({id:5,image:"/assets/img/food-2.jpg",description:"Food photo 2",category:"food",author:"Eiliv-Sonas Aceron",date:"2017-06-24T22:00:00.000Z"}).onConflict('id').ignore();
          await trx('images').insert({id:6,image:"/assets/img/wildlife-4.jpg",description:"Wildlife photo 4",category:"wildlife",author:"Filippo Hannum",date:"2015-03-10T23:00:00.000Z"}).onConflict('id').ignore();
          await trx('images').insert({id:7,image:"/assets/img/food-3.jpg",description:"Food photo 3",category:"food",author:"Ringo Crockett",date:"2018-08-13T22:00:00.000Z"}).onConflict('id').ignore();
          await trx('images').insert({id:8,image:"/assets/img/nature-3.jpg",description:"Nature photo 3",category:"nature",author:"Ulla McGivena",date:"2017-05-20T22:00:00.000Z"}).onConflict('id').ignore();
          await trx('images').insert({id:9,image:"/assets/img/architecture-2.jpg",description:"Architecture photo 2",category:"architecture",author:"Liam Pozz",date:"2015-04-10T22:00:00.000Z"}).onConflict('id').ignore();
          await trx('images').insert({id:10,image:"/assets/img/nature-4.jpg",description:"Nature photo 4",category:"nature",author:"Dulci Morrott",date:"2017-12-02T23:00:00.000Z"}).onConflict('id').ignore();
          await trx('images').insert({id:11,image:"/assets/img/architecture-3.jpg",description:"Architecture photo 3",category:"architecture",author:"Joel Filipe",date:"2019-06-23T22:00:00.000Z"}).onConflict('id').ignore();
          await trx('images').insert({id:12,image:"/assets/img/fineart-1.jpg",description:"Fine Art photo 1",category:"fine art",author:"Jue Huang",date:"2015-11-26T23:00:00.000Z"}).onConflict('id').ignore();
          await trx('images').insert({id:13,image:"/assets/img/food-4.jpg",description:"Food photo 4",category:"food",author:"Felice Summerside",date:"2015-08-16T22:00:00.000Z"}).onConflict('id').ignore();
          await trx('images').insert({id:14,image:"/assets/img/food-5.jpg",description:"Food photo 5",category:"food",author:"Thomasin Osment",date:"2017-09-22T22:00:00.000Z"}).onConflict('id').ignore();
          await trx('images').insert({id:15,image:"/assets/img/nature-1.jpg",description:"Nature photo 1",category:"nature",author:"Brian Krahl",date:"2018-02-06T23:00:00.000Z"}).onConflict('id').ignore();
          await trx('images').insert({id:16,image:"/assets/img/wildlife-1.jpg",description:"Wildlife photo 1",category:"wildlife",author:"Rakel Lumox",date:"2018-05-25T22:00:00.000Z"}).onConflict('id').ignore();
          await trx('images').insert({id:17,image:"/assets/img/fineart-2.jpg",description:"Fine Art photo 2",category:"fine art",author:"Raychan Jones",date:"2019-03-13T23:00:00.000Z"}).onConflict('id').ignore();
          await trx('images').insert({id:18,image:"/assets/img/architecture-4.jpg",description:"Architecture photo 4",category:"architecture",author:"Claudio Testa",date:"2015-01-03T23:00:00.000Z"}).onConflict('id').ignore();
          await trx('images').insert({id:19,image:"/assets/img/wildlife-2.jpg",description:"Wildlife photo 2",category:"wildlife",author:"Timmie Middlebrook",date:"2018-10-02T22:00:00.000Z"}).onConflict('id').ignore();
          await trx('images').insert({id:20,image:"/assets/img/fineart-3.jpg",description:"Fine Art photo 3",category:"fine art",author:"Federico Passi",date:"2015-11-13T23:00:00.000Z"}).onConflict('id').ignore();
      
          // Process users
          await trx('users').del();
          await trx('users').insert({id:1,first_name:"Rowena",last_name:"Pardy",gender:"Female",email:"rpardy0@unc.edu",company:"Lehner, Langworth and Hagenes",avatar:"/assets/img/avatar-1.jpg"}).onConflict('id').ignore();
          await trx('users').insert({id:2,first_name:"Rae",last_name:"De Bruyne",gender:"Female",email:"rdebruyne1@aboutads.info",company:"Bauch-Trantow",avatar:"/assets/img/avatar-2.jpg"}).onConflict('id').ignore();
          await trx('users').insert({id:3,first_name:"Janeczka",last_name:"Darke",gender:"Female",email:"jdarke2@google.co.jp",company:"Towne, Koch and Wyman",avatar:"/assets/img/avatar-3.jpg"}).onConflict('id').ignore();
          await trx('users').insert({id:4,first_name:"Niki",last_name:"Ehlerding",gender:"Male",email:"nehlerding3@msu.edu",company:"Rolfson, Nienow and Morar",avatar:"/assets/img/avatar-7.jpg"}).onConflict('id').ignore();
          await trx('users').insert({id:5,first_name:"Davidde",last_name:"Hansbury",gender:"Male",email:"dhansbury4@nyu.edu",company:"Bailey, Smitham and Runte",avatar:"/assets/img/avatar-8.jpg"}).onConflict('id').ignore();
          await trx('users').insert({id:6,first_name:"Adan",last_name:"Sunnucks",gender:"Male",email:"asunnucks5@unblog.fr",company:"Flatley-Hackett",avatar:"/assets/img/avatar-9.jpg"}).onConflict('id').ignore();
          await trx('users').insert({id:7,first_name:"Hugh",last_name:"Gallen",gender:"Male",email:"hgallen6@boston.com",company:"Jakubowski-Crist",avatar:"/assets/img/avatar-10.jpg"}).onConflict('id').ignore();
          await trx('users').insert({id:8,first_name:"Elva",last_name:"Abbots",gender:"Female",email:"eabbots7@sourceforge.net",company:"Kshlerin, Fadel and Kunze",avatar:"/assets/img/avatar-4.jpg"}).onConflict('id').ignore();
          await trx('users').insert({id:9,first_name:"Willem",last_name:"O'Hickey",gender:"Male",email:"wohickey8@goo.ne.jp",company:"Wisoky Group",avatar:"/assets/img/avatar-11.jpg"}).onConflict('id').ignore();
          await trx('users').insert({id:10,first_name:"Major",last_name:"Dilkes",gender:"Male",email:"mdilkes9@yahoo.com",company:"Turcotte LLC",avatar:"/assets/img/avatar-12.jpg"}).onConflict('id').ignore();
          await trx('users').insert({id:11,first_name:"Rudolfo",last_name:"Gabbat",gender:"Male",email:"rgabbata@list-manage.com",company:"Doyle and Sons",avatar:"/assets/img/avatar-13.jpg"}).onConflict('id').ignore();
          await trx('users').insert({id:12,first_name:"Egor",last_name:"Brombell",gender:"Male",email:"ebrombellb@blogger.com",company:"Ondricka LLC",avatar:"/assets/img/avatar-14.jpg"}).onConflict('id').ignore();
          await trx('users').insert({id:13,first_name:"Page",last_name:"Feeny",gender:"Male",email:"pfeenyc@unblog.fr",company:"Jerde, Schmidt and Schumm",avatar:"/assets/img/avatar-15.jpg"}).onConflict('id').ignore();
          await trx('users').insert({id:14,first_name:"Riordan",last_name:"Pitkeathly",gender:"Male",email:"rpitkeathlyd@discuz.net",company:"Kilback, Halvorson and Torp",avatar:"/assets/img/avatar-16.jpg"}).onConflict('id').ignore();
          await trx('users').insert({id:15,first_name:"Herold",last_name:"Smithend",gender:"Male",email:"hsmithende@google.co.uk",company:"Steuber-Tillman",avatar:"/assets/img/avatar-17.jpg"}).onConflict('id').ignore();
          await trx('users').insert({id:16,first_name:"Simone",last_name:"Feaveer",gender:"Female",email:"sfeaveerf@imageshack.us",company:"Spencer Group",avatar:"/assets/img/avatar-5.jpg"}).onConflict('id').ignore();
          await trx('users').insert({id:17,first_name:"Sim",last_name:"Leaton",gender:"Male",email:"sleatong@google.nl",company:"Wuckert Group",avatar:"/assets/img/avatar-18.jpg"}).onConflict('id').ignore();
          await trx('users').insert({id:18,first_name:"Malvin",last_name:"Markushkin",gender:"Male",email:"mmarkushkinh@yale.edu",company:"Lockman Inc",avatar:"/assets/img/avatar-19.jpg"}).onConflict('id').ignore();
          await trx('users').insert({id:19,first_name:"Darnall",last_name:"De Vile",gender:"Male",email:"ddevilei@marriott.com",company:"Wisoky, Kiehn and Berge",avatar:"/assets/img/avatar-20.jpg"}).onConflict('id').ignore();
          await trx('users').insert({id:20,first_name:"Jaquelyn",last_name:"Sinnatt",gender:"Female",email:"jsinnattj@cyberchimps.com",company:"Lebsack, Wisozk and Kuhlman",avatar:"/assets/img/avatar-6.jpg"}).onConflict('id').ignore();
      
      })
      
      })
};

exports.down = function(knex) {
  return knex.schema
    .dropTable('users')
    .dropTable('images')
    .dropTable('countries')
    .dropTable('cars')
};
